### ISSUE TITLE
Console.log does not show up

### ISSUE THREAD

**Issue by izrobin** [actions/javascript-action#27]
Hi!

I see that you're printing `console.log('Waiting ${ms} milliseconds ...')` in your [action code](https://github.com/actions/javascript-action/blob/master/index.js#L9), but I can't see it when the action runs. Is it supposed to be like this? How would one output this properly?

Thanks

**Comment by hross** [comment]
Fixed to use info/debug output and added comment on how to use it: https://github.com/actions/javascript-action/pull/36

**Comment by TomasHubelbauer** [comment]
@hross Is there any way to make it so that plain `console.log` calls propagate to the output of the custom Action? It isn't always preferable or possible to use `@actions/core` and its logging methods. I tried direct `process.stdout.write` too but I just can't get my script to output to the workflow that is using my custom Action.
